apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: queueapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queueapp
  template:
    metadata:
      labels:
        app: queueapp
        release: '1'
    spec:
      containers:
      - name: queueapp
        image: richardchesterwood/k8s-fleetman-queue:release1

---
apiVersion: v1
kind: Service
metadata:
  name: queueapp
spec:
  selector:
    app: queueapp
    release: '1'
  ports:
  - name: http
    port: 8161
    nodePort: 30010
  type: NodePort
